# Generated by Django 4.0.5 on 2022-10-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_conta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conta',
        ),
    ]
